version: "3.9"
services:
  hoover_bot:
    build: ./hoover_bot
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - ./redis-volume:/data
#  datadog:
#    image: "public.ecr.aws/datadog/docker-dd-agent"
